[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'
[project]
name = "bayesian_models"
version = "0.0.1"
authors = [
  { name="Alexander Rodis", email="alexanderrhodis@gmail.com" },
]
maintainers = [
    { name="Alexander Rodis", email="alexanderrhodis@gmail.com" },
]
description = "A package for building common bayesian models in pymc"
readme = 'README.md'
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT Licence",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/AlexRodis/bayesian_models"
"Bug Tracker" = "https://github.com/AlexRodis/bayesian_models/issues"

[tool.setuptools]
py-modules = []
